Units network techs
UU-ER/EHUB-Py pull request #194
Opened 2024-05-30 13:04 UTC by lucabert01

Added the units to the network techs. I saw that techs like trucks and ships are not set to size_is_int =1. However, I didn't change it as the data about the size were not the ones of a unit (so I would need to fetch the size data for each tech, which I might be doing at some point but it doesn't look like a pyhub priority to me)

2024-05-30 15:21 UTC, JeanWi requested changes
Looks good other than:
- fix pull request: not on main but on develop 0.1.0 (you can do that best on github by editing the pull request)
- fix the indents in the json files
- be consistent with tonne/h or t/h (or is that on purpose?)

2024-05-31 12:30 UTC, lucabert01 reviewed
Indexing in json fixed, t and tonne now are consistent

2024-05-31 12:34 UTC, julia1071 approved these changes

2024-06-04 13:48 UTC, JeanWi approved these changes

2024-06-05 08:13 UTC, merged